# name: push  project_1 docker image to ECR 
# on: 
#   push:
#     branches:
#       - 'main'
#     paths:
#       - ' project_1_wordpress/**'
      

# jobs: 
#   running_shell_command:
#     runs-on: ubuntu-latest
#     steps: 
#       - name: cloning git repo  
#         uses: actions/checkout@v2
      
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ap-south-1

#       - name: Login to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v1

#       - name: Build, tag, and push image to Amazon ECR
#         env:
#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           ECR_REPOSITORY: wordpress_am
#           IMAGE_TAG:  project_1
#         run: |
#           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG  project_1_wordpress/.
#           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG